import { Inter } from 'next/font/google'
import './globals.css'
import NavbarPage from '@/components/Navbar';
import {Providers} from "./providers";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Portafolio DV',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es" className='dark'>

      <body className={inter.className}>
        <Providers>
          <NavbarPage/>

          {children}
        </Providers>
        </body>
    </html>
  )
}
